name: Continuous Integration

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - develop

jobs:
    build_artefacts:
        runs-on: ubuntu-latest

        steps:
            - name: Set up package
              id: action_ts_setup_repo
              uses: youwol/nestor/ts/set_up_repo@main
              with:
                  ref: ${{ github.ref }}
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Static analysis code source
              id: action_ts_static_analysis
              uses: youwol/nestor/ts/static_analysis@main

            - name: Build & test package
              id: action_ts_build_artefact
              uses: youwol/nestor/ts/build_and_test@main
