name: Make release

on:
  workflow_dispatch:
    inputs:
      version:
        description: version to release
        required: true
        type: string

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name: Make release
        id: make_release
        uses: youwol/nestor/ts/release@test_release
        with:
          version: ${{ github.event.inputs.version }}
          nestor_gpg_priv: ${{ secrets.NESTOR_GPG_PRIV }}
          nestor_github_pat: ${{ secrets.NESTOR_GITHUB_PAT }}
